
server:
  error:
    include-message: always
    include-binding-errors: always

spring:
  datasource:
    password: mellon
    url: jdbc:mysql://${MYSQL_HOST:localhost}:3306/registration?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
    username: root
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        format_sql: true
    show-sql: true
